"""Add Resume table

Revision ID: d05a332f25ad
Revises: a4c4165443f8
Create Date: 2025-12-10 10:40:34.085817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel        
import pgvector          
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'd05a332f25ad'
down_revision: Union[str, Sequence[str], None] = 'a4c4165443f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resumes')
    # ### end Alembic commands ###
