"""Add ESCO tables

Revision ID: 42fbd550efd6
Revises: 8bcbcc308193
Create Date: 2026-02-24 15:09:59.338358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '42fbd550efd6'
down_revision: Union[str, Sequence[str], None] = '8bcbcc308193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esco_skills',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('skill_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esco_skills_name'), 'esco_skills', ['name'], unique=False)
    op.create_table('esco_relations',
    sa.Column('source_skill_id', sa.Integer(), nullable=False),
    sa.Column('target_skill_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_skill_id'], ['esco_skills.id'], ),
    sa.ForeignKeyConstraint(['target_skill_id'], ['esco_skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esco_relations_relation_type'), 'esco_relations', ['relation_type'], unique=False)
    op.create_index(op.f('ix_esco_relations_source_skill_id'), 'esco_relations', ['source_skill_id'], unique=False)
    op.create_index(op.f('ix_esco_relations_target_skill_id'), 'esco_relations', ['target_skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_esco_relations_target_skill_id'), table_name='esco_relations')
    op.drop_index(op.f('ix_esco_relations_source_skill_id'), table_name='esco_relations')
    op.drop_index(op.f('ix_esco_relations_relation_type'), table_name='esco_relations')
    op.drop_table('esco_relations')
    op.drop_index(op.f('ix_esco_skills_name'), table_name='esco_skills')
    op.drop_table('esco_skills')
    # ### end Alembic commands ###
