"""add_task_state_tables

Revision ID: 8bcbcc308193
Revises: f4f861046e17
Create Date: 2026-02-24 13:14:08.344771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8bcbcc308193'
down_revision: Union[str, Sequence[str], None] = 'f4f861046e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('idle', 'working', 'paused', 'success', 'failed', name='taskstatus'), nullable=False),
    sa.Column('current_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('context_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('missing_fields', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_states_user_id'), 'task_states', ['user_id'], unique=False)
    op.create_table('decision_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_state_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_state_id'], ['task_states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_audits_task_state_id'), 'decision_audits', ['task_state_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_audits_task_state_id'), table_name='decision_audits')
    op.drop_table('decision_audits')
    op.drop_index(op.f('ix_task_states_user_id'), table_name='task_states')
    op.drop_table('task_states')
    # ### end Alembic commands ###
