"""Add profile fields

Revision ID: f8ed2280fe22
Revises: addbefcfa8d8
Create Date: 2026-02-27 12:55:11.343440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f8ed2280fe22'
down_revision: Union[str, Sequence[str], None] = 'addbefcfa8d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidateprofile', sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidateprofile', sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('candidateprofile', sa.Column('experience', sa.JSON(), nullable=True))
    op.add_column('candidateprofile', sa.Column('education', sa.JSON(), nullable=True))
    op.add_column('candidateprofile', sa.Column('certifications', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidateprofile', 'certifications')
    op.drop_column('candidateprofile', 'education')
    op.drop_column('candidateprofile', 'experience')
    op.drop_column('candidateprofile', 'summary')
    op.drop_column('candidateprofile', 'headline')
    # ### end Alembic commands ###
